### ISSUE TITLE
Support self signed certificate for local development

### ISSUE THREAD

**Issue by 0xAlcibiades** [bufbuild/connect-query#37]
How might a transport accept a self signed certificate or different root authority for a local dev environment? Been scouring the docs and function signatures.

**Comment by dimitropoulos** [comment]
There are some [docs](https://connect.build/docs/node/getting-started/#use-the-grpc-protocol-instead-of-the-connect-protocol) for this on Connect-Node.  Does that help?

You may also want to take a look at the `credentials` field you can pass to `createConnectTransport`:
<img width="50%" src="https://user-images.githubusercontent.com/15232461/234574541-af90c7f0-d09e-4146-b8b7-16f6496f82f9.png" />

**Comment by timostamm** [comment]
Hey @0xAlcibiades, I assume you are running connect-query in the browser? Then the only option is to tell your browser to trust the certificate. It is not possible to do so from a JS environment in the browser (and if you think about it, it makes a lot of sense).

[mkcert](https://github.com/FiloSottile/mkcert) is commonly used to generate locally trusted certificates. It installs a certificate authority for your browser, and if you run the API server locally with a certificate chained to this CA, your browser will trust the server.

If you are not running in browser but in Node.js, you can use a transport from `@bufbuild/connect-node` - they offer the standard Node.js options because they use the Node.js APIs under the hood, while the transports from `@bufbuild/connect-web` use the fetch API.

Does this help you to solve the problem?

**Comment by dimitropoulos** [comment]
hey @0xAlcibiades gonna close this issue because I think we've answered the question, but if not please let us know and we can reopen :)
